name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  eval:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-linux
            os: ubuntu-26.04-arm
          - system: aarch64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

      - name: Setup Cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: starrynix-derivations
          extraPullNames: nix-community
          skipPush: true

      - name: Evaluate Derivations
        run: |
          all_drvs="$(nix run nixpkgs#nix-eval-jobs -- --flake '.#ciPackages.${{ matrix.system }}.active' --force-recurse --check-cache-status)"
          unbuilt_drvs="$(echo "${all_drvs}" | jq --compact-output '
            select (.cacheStatus == "notBuilt")
            | {
              attr,
              attrPath,
              system,
              os: "${{ matrix.os }}",
            }
          ')"
          echo "${unbuilt_drvs}" | jq
          echo "${unbuilt_drvs}" > eval-${{ matrix.system }}

      - name: Upload Evaluation Result
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: eval-${{ matrix.system }}
          path: eval-${{ matrix.system }}

  aggregate:
    needs: eval
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.aggregate.outputs.matrix }}

    steps:
      - name: Download Per-System Evaluation Results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: eval-*
          merge-multiple: true
          path: eval-results

      - name: Aggregate Evaluation Results
        id: aggregate
        run: |
          concat_drvs="$(cat eval-results/* | jq --slurp --compact-output)"
          echo "${concat_drvs}" | jq

          # GHA requires that at least one entry is presented in the matrix.
          matrix="$(echo "${concat_drvs}" | jq --compact-output '
            if length == 0 then
              [{
                attr: "__skip_build",
                attrPath: ["__skip_build"],
                system: "x86_64-linux",
                os: "ubuntu-latest",
                skip: true
              }]
            else
              map(. + { skip: false })
            end
          ')"
          echo "matrix=${matrix}" >> ${GITHUB_OUTPUT}

  build:
    needs: aggregate
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.aggregate.outputs.matrix) }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        if: ${{ !matrix.skip }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        if: ${{ !matrix.skip }}
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

      - name: Setup Cachix
        if: ${{ !matrix.skip }}
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: starrynix-derivations
          extraPullNames: nix-community
          skipPush: true
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Derivation ${{ matrix.attr }}
        if: ${{ !matrix.skip }}
        run: |
          out_paths="$(nix build '.#ciPackages.${{ matrix.system }}.active.${{ matrix.attr }}' -L --print-out-paths)"
          if [[ "$?" -eq 0 ]]; then
            echo "${out_paths}"
            if [[ '${{ github.ref == 'refs/heads/main' }}' == 'true' ]]; then
              echo "${out_paths}" | cachix push starrynix-derivations
            fi
          fi

